---

- name: Install nginx from EPEL
  yum: name=nginx state=latest
  tags: nginx

- name: Create SSL Directory
  file: path=/etc/nginx/ssl state=directory

- name: create ssl vhost
  template: src=ssl_vhost.conf dest=/etc/nginx/conf.d/{{ server_name }}.conf backup=yes
  notify: reload nginx

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=UK/ST=London/L=London/O=IT/CN={{server_name}}" -days 3650 -keyout /etc/nginx/ssl/{{ server_name }}.key -out /etc/nginx/ssl/{{ server_name }}.crt -extensions v3_ca creates=/etc/nginx/ssl/{{ server_name }}.crt
  when: use_self_signed_cert == "yes"
  notify: reload nginx

- name: copy signed SSL cert
  copy: src={{ server_name }}.crt dest=/etc/nginx/ssl/{{ server_name }}.crt
  when: use_self_signed_cert != "yes"
  notify: reload nginx

- name: disable http
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify: restart nginx
