---

- name: restart graylog2-server
  service: name=graylog2-server state=restarted

- name: restart graylog2-web
  service: name=graylog2-web state=restarted

- name: Add input into graylog
  shell: 'sleep 20; curl -X POST -H "Content-Type: application/json" -d "`cat /root/input_add.json`" http://admin:{{ root_password_unencrypted }}@127.0.0.1:12900/system/inputs'

