---

- name: Adding graylog2 repo
  yum: name=https://packages.graylog2.org/repo/packages/graylog2-{{ graylog2_version }}-repository-el6_latest.rpm state=present
  tags: graylog2

- name: Install graylog2-server and graylog2-web-interface
  yum: name={{ item }} state=latest disable_gpg_check=yes
  tags: graylog2
  with_items:
    - graylog2-server
    - graylog2-web

- name: configure graylog2-server
  template: src=graylog2.conf.j2 dest=/etc/graylog2.conf backup=yes
  notify: restart graylog2-server

- name: configure graylog2-web
  template: src=graylog2-web-interface.conf.j2 dest=/etc/graylog2/web/graylog2-web-interface.conf backup=yes
  notify: restart graylog2-web

- name: Make sure service graylog2-server is added to startup
  service: name=graylog2-server state=started enabled=yes
  tags: graylog2

- name: Make sure service graylog2-web is added to startup
  service: name=graylog2-web state=started enabled=yes
  tags: graylog2

- name: Copy input json to server
  template: src=input_add.json.j2 dest=/etc/graylog2/input_add.json
  notify: Add input into graylog
  tags: input_add

